package com.samiulsifat.task_management.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;

@DynamoDBTable(tableName = "Tasks")
public class Task {

    @DynamoDBHashKey(attributeName = "taskId")
    @DynamoDBAutoGeneratedKey
    private String taskId;
    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "UserNameIndex", attributeName = "username")
    private String username;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private String status;
    @DynamoDBAttribute
    private String createdAt;
    @DynamoDBAttribute
    private String dueDate;
    @DynamoDBAttribute
    private String assignedBy;
    @DynamoDBAttribute
    private String assignedTo;

    public Task(
            String taskId,
            String username,
            String title,
            String description,
            String status,
            String dueDate,
            String assignedBy,
            String assignedTo) {
        this.taskId = taskId;
        this.username = username;
        this.title = title;
        this.description = description;
        this.status = status;
        this.createdAt = String.valueOf(new Date().getTime());
        this.dueDate = dueDate;
        this.assignedBy = assignedBy;
        this.assignedTo = assignedTo;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public String getAssignedBy() {
        return assignedBy;
    }

    public void setAssignedBy(String assignedBy) {
        this.assignedBy = assignedBy;
    }

    public String getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }
}
